apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  annotations:
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
